Automatically update java client (ref: Cosmo-Tech/cosmotech-api@efef128edec46d3748194fd78b2141920aea9fb5)
===
No longer define and set the deprecated 'allowedTelemetry' Cosmos property

Fix Quorum size not met issue with the default Azure Cosmos Health Indicator

For some reason, the default Cosmos Health Indicator (which just attempts to read the database)
suddenly returns the following error, along with way too verbose stack traces,
which adds some clutter to the service logs:

===
2021-08-25 20:44:39.119  WARN 1 --- [s-rntbd-nio-2-2] c.a.c.i.directconnectivity.QuorumReader  : Could not complete read quorum with read quorum value of 2
2021-08-25 20:44:39.119 ERROR 1 --- [s-rntbd-nio-2-2] reactor.core.publisher.Operators         : Operator called default onErrorDropped
  com.azure.cosmos.implementation.GoneException: {innerErrorMessage:READ Quorum size of 2 is not met for the request.}
  at com.azure.cosmos.implementation.directconnectivity.QuorumReader.lambda(QuorumReader.java:249)
  at reactor.core.publisher.FluxDefer.subscribe(FluxDefer.java:46)
  at reactor.core.publisher.Flux.subscribe(Flux.java:8411)
  at reactor.core.publisher.FluxConcatArray.onComplete(FluxConcatArray.java:255)
  at reactor.core.publisher.FluxTakeUntil.onComplete(FluxTakeUntil.java:121)
  at reactor.core.publisher.FluxTakeUntil.onNext(FluxTakeUntil.java:99)
  - OMITTED FOR BREVITY -
===

This behavior has been fixed by providing our own Health Indicator,
which, at this time, executes a simple COUNT SQL query on the organizations container.

Use a more concise form for defining logging levels
===

Co-authored-by: rm3l <rm3l@users.noreply.github.com>